# Generated by Django 3.2.5 on 2021-08-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_machine_consumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
